[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_lend_borrow = "AM8eBHrkMbeNFYQrYPLzVfhFbBweCSQk1dUvPm7H78vZ"

[programs.devnet]
nft_lend_borrow = "AM8eBHrkMbeNFYQrYPLzVfhFbBweCSQk1dUvPm7H78vZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
